name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger workflow on pushes to 'main' branch

jobs:
  # Step 1: Build the Docker Image and Push to Docker Hub
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: saugat0082/catalogservice:latest

  # Step 2: Deploy Services Using Docker Compose
  deploy:
    runs-on: ubuntu-latest
    needs: docker  # Only run after the docker job

    steps:
      # Deploy to remote server using SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_SERVER_IP }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }} # Use SSH key instead of password for better security
          script: |
            cd /path/to/your/docker-compose-folder
            docker-compose pull
            docker-compose up -d --build --remove-orphans
