name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger workflow on pushes to 'master' branch

jobs:
  # Step 1: Build the Docker Image and Push to Docker Hub
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Extract Docker credentials directly from the secret
      - name: Extract Docker Credentials
        run: |
          export DOCKER_USERNAME=$(echo '${{ secrets.catalogsecrets }}' | jq -r '.DOCKER_USERNAME')
          export DOCKER_PASSWORD=$(echo '${{ secrets.catalogsecrets }}' | jq -r '.DOCKER_PASSWORD')
          echo "DOCKER_USERNAME=$DOCKER_USERNAME" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=$DOCKER_PASSWORD" >> $GITHUB_ENV

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      # Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: saugat0082/catalogservice:latest
