name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger workflow on pushes to 'master' branch

jobs:
  # Step 1: Build the Docker Image and Push to Docker Hub
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Extract Docker credentials from catalogsecrets
      - name: Extract Docker Credentials
        id: docker-credentials
        run: |
          echo "${{ secrets.catalogsecrets }}" > credentials.json
          export DOCKER_USERNAME=$(cat credentials.json | jq -r '.DOCKER_USERNAME')
          export DOCKER_PASSWORD=$(cat credentials.json | jq -r '.DOCKER_PASSWORD')
          echo "::set-output name=username::$DOCKER_USERNAME"
          echo "::set-output name=password::$DOCKER_PASSWORD"

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ steps.docker-credentials.outputs.username }}
          password: ${{ steps.docker-credentials.outputs.password }}

      # Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: saugat0082/catalogservice:latest
